#!/bin/bash
#@ wall_clock_limit = 48:00:00   
#@ initialdir = /gpfs/res_scratch/astro/canasg/Crowd_Dynamics/
#@ error = error_file_script
#@ output = output_file_script
#@ total_tasks = 1
#@ cpus_per_task = 16
#@ tasks_per_node = 1
matlab -nodesktop -nodisplay -nosplash < scriptcrowdsG.m
